version: '3.3'

services:
  db:
    image: mysql:5.7
    volumes:
      - dev_db_data:/var/lib/mysql
    restart: always
    env_file:
      - .env


  wordpress:
    image: wordpress:latest
    depends_on:
      - db
    ports:
      - "8000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
    env_file:
      - .env
    volumes:
      - ./uploads:/var/www/html/wp-content/uploads
      - ./themes:/var/www/html/wp-content/themes
      - ./plugins/custom-post-type-ui:/var/www/html/wp-content/plugins/custom-post-type-ui
      - ./plugins/custom-field-suite:/var/www/html/wp-content/plugins/custom-field-suite
      - ./plugins/custom-post-type-permalinks:/var/www/html/wp-content/plugins/custom-post-type-permalinks
volumes:
  dev_db_data:
